### ISSUE TITLE
Upgrade to 10.5.17?

### ISSUE THREAD

**Issue by PalminX** [Tob1as/docker-mariadb#9]
Is there any chance getting the 10.5 version bumped to 10.5.17?

For use in the new Home Assistant 2023.2, it is recommended to update MariaDB to 10.5.17, see https://community.home-assistant.io/t/2023-2-how-can-i-assist/528637/3

Currently, this seems to be the only working image for Raspberry Pi deployments, so an update would be appreciated.

**Comment by Tob1as** [comment]
I have run the build pipline yesterday again for 10.5.
The Image with Tag `10.5` (debian) has now Version 10.5.18 and `10.5-alpine` has now 10.5.17. Ubuntu don't build.

But I recommend switching to 10.6! This is the [LTS](https://endoflife.date/mariadb) version of MariaDB and I will not maintain older image versions, since I no longer use them myself. And the Image `10.5-alpine` based on Alpine Version 3.14 is in 2 months [EOF](https://endoflife.date/alpine).

**Comment by PalminX** [comment]
Thanks a lot!

**Comment by Tob1as** [comment]
I update/rebuild the 10.5 image(s).... when you use TAG 10.5 (debian) then use in futur 10.5-debian  :wink:

**Note**: However, I have only performed a simple functional test. So please make a backup before changing. For example see [here](https://github.com/Tob1as/docker-mariadb/issues/10#issuecomment-1433701483)
